### ISSUE TITLE
Hi, I'm a master from China

### ISSUE THREAD

**Issue by MontaEllis** [KeisukeShimokawa/papers-challenge#118]
Hi, I'm a master from China. I've read your paper arrangement. I want to work with you to manage a more complete paper arrangement. Can I join you?

**Comment by KeisukeShimokawa** [comment]
Hi, thank you for caring about this repository!

I am Japanese, and I write summaries in Japanese of the content of the papers I read. And the purpose of this repository is to summarize the content and replicated implementations of the papers I've read myself.

I will continue to write summaries of the papers I read in Japanese. So may I ask you how you plan to do the arrangement of the papers? In English?

**Comment by MontaEllis** [comment]
> 
> 
> Hi, thank you for caring about this repository!
> 
> I am Japanese, and I write summaries in Japanese of the content of the papers I read. And the purpose of this repository is to summarize the content and replicated implementations of the papers I've read myself.
> 
> I will continue to write summaries of the papers I read in Japanese. So may I ask you how you plan to do the arrangement of the papers? In English?

Yes! I've prepared some summaries of the papers I read. How we communicate ？Do you have  e-mail? Or Facebook? Or Wechat(one of Chinese communication software).

**Comment by KeisukeShimokawa** [comment]
Hi

I have created this repository only to summarize the papers I have read. Against this background, a situation where multiple languages get mixed up in issues is undesirable.

Your offer is very much appreciated, but for these reasons, you might want to try a different repository when doing a roundup.
